### PR TITLE
Searching and Sorting Algorithms with C++

### PR DESCRIPTION
**Pull request by Siddhant-K-code**
# Algorithms
## Searching
- [x] Binary Search
- [x] Fibonacci Search
- [x] Linear Search
- [x] Ternary Search

## Sorting

- [x] Merge Sort
- [x] Quick Sort
- [x] Selection Sort
- [x] Insertion Sort
- [x] Heap Sort
- [x] Bubble Sort

### CODE REVIEW

**Comment by Siddhant-K-code** [comment]
Thanks @ShreyaDhir

**Comment by ever-cell** [comment]
That's a lot of quality contribution. Thank you so much for it!

**Comment by Siddhant-K-code** [comment]
I will Add More Algorithms @ShreyaDhir , Soon

**Comment by ever-cell** [comment]
Sure!

**Comment by Siddhant-K-code** [comment]
Pls approve my PR, so Hacktoberfest  accepted it

**Review by ever-cell — COMMENTED** [review]
Looking positive!

**Pull request merged**
